name: Push package for veracode scan

on: [push]
#  pull_request:
#    types: [closed]
#    branches:
#      - master

jobs:
#  pre:
#    runs-on: ubuntu-latest
#    outputs:
#      skip: ${{ steps.skip-check.outputs.should_skip }}
#    steps:
#    - id: skip-check
#      uses: fkirc/skip-duplicate-actions@master
#      with:
#        github_token: ${{ github.token }}
#        paths_ignore: '["**.md", "dev/**"]'
  veracode-scan:
    name: veracode scan
    runs-on: ubuntu-latest
    needs: pre
    steps:
    - uses: actions/checkout@v2
      if: ${{ github.event.pull_request.merged }}
      with:
        ref: master
    - run: wget https://search.maven.org/remotecontent?filepath=com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/19.6.5.8/vosp-api-wrappers-java-19.6.5.8.jar -O vosp-api-wrappers-java-19.6.5.8.jar
    - run: tar chfz buildpack.tar.gz buildpack
    - run: java -jar vosp-api-wrappers-java-19.6.5.8.jar -vid ${{ veracode.api.id }} -vkey ${{ veracode.api.key }} -action UploadFile -appid ${{ veracode.app.id }} -sandboxid ${{ veracode.sandbox.id }} -filepath buildpack.tar.gz
    - run: java -jar vosp-api-wrappers-java-19.6.5.8.jar -vid ${{ veracode.api.id }} -vkey ${{ veracode.api.key }} -action BeginPreScan -appid ${{ veracode.app.id }} -sandboxid ${{ veracode.sandbox.id }} -autoscan true
